version: '3.9'

services:
  bookshelf:
    container_name: bookshelf
    image: bookshelf
    hostname: bookshelf
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      # - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_HOST=${HOSTNAME}
    command: npm start
